### ISSUE TITLE
Add support for Argo artifacts

### ISSUE THREAD

**Issue by tachyus-ryan** [argoproj-labs/hera-workflows#13]
Argo Workflows supports input and output artifacts in a template, and a workflow step may specify an artifact argument. These can fully specify the artifact repository inline or use a key-only approach. Depending on the executor, a volume may need to be provided for output artifacts. Support for this feature needs to handle all these options.

Hera has a nice design, and I'm not sure how to add this support without beginning to make the API messier. Do you have thoughts on how to add this while retaining the Hera style?

References:
* [Key-Only Artifacts](https://argoproj.github.io/argo-workflows/key-only-artifacts/)
* [Example](https://github.com/argoproj/argo-workflows/blob/master/examples/artifact-passing.yaml)

**Comment by flaviuvadan** [comment]
This would be a great addition, for the reasons you mentioned! I will look through what this might require and come back with some suggestions we may discuss.

**Comment by flaviuvadan** [comment]
@tachyus-ryan I started working on this today and I think I have a path forward. I am currently trying to determine how to best abstract away the GCS/S3/HTTP/etc. specifications from the artifacts so users focus only on the task artifact input, task artifact output, etc. Specifying those is also interesting because of the intersection between the two concepts (I/O artifact), with the main difference being that the input artifact requires a task name. I will report back when I have a PR; will also tag you in it.

**Comment by tachyus-ryan** [comment]
@flaviuvadan thank you very much!
