### ISSUE TITLE
CronWorkflow update command

### ISSUE THREAD

**Issue by kitagry** [argoproj-labs/hera-workflows#133]
Hi maintainers.
I want to use hera-workflows to deploy system.

In order to do it, I want to update the previous CronWorkflow.
To achieve it, hera-workflows should have following options.

* option to skip name suffix
  *  https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/cron_workflow.py#L84
* CronWorkflow.update command

I want to create PR, if it is ok.

Thank you.

**Comment by flaviuvadan** [comment]
Hi @kitagry! The name suffix was brought up in a different conversation as well in order to support actions like the one you mentioned - users want to name their workflows in one way and Hera not modify the name on their behalf, so users can perform update, delete, get, etc. Maybe it's time to remove that from Hera and, since it's a breaking change, it will be released under version 3.0.0. I will mark this as an enhancement!
