### ISSUE TITLE
Add conditional execution anySucceeded/AllFailed (orig: Fail to resolve task status when task has input_from)

### ISSUE THREAD

**Issue by bnuzhanyu** [argoproj-labs/hera-workflows#135]
I try to use condition on_error, on_failure for task dependency, but got an error:
`failed to resolve {{tasks.sql.status}}`
When I remove sql_task's input_from, it works well. 
I thought it was caused by argo-workflow, but I can't figure out.

```python
from hera.input import InputFrom
from hera.task import Task
from hera.workflow import Workflow
from hera.workflow_service import WorkflowService

def context_config():
    import json, sys
    day = '2022-04-01'
    job_config = {
        "sql": f"select * from table where day='{day}'",
    }
    json.dump([{'context' : job_config}], sys.stdout)
    
def sql(context):
    print('success')

def success(context):
    print("success")

def error_handle(context):
    print("error")

def start():
    ws = WorkflowService('xxxx', verify_ssl=False, token=get_argo_token())
    w = Workflow('condition-test', ws, namespace='argo')
    tasks = []
    ctx_task_name = 'ctx-gen'
    ctx_gen = Task(ctx_task_name, context_config)
    tasks.append(ctx_gen)
    sql_task = Task('sql', sql, input_from=InputFrom(name=ctx_task_name, parameters=['context']))
    tasks.append(sql_task)
    ctx_gen.next(sql_task)

    err_task = Task('error', error_handle, input_from=InputFrom(name=ctx_task_name, parameters=['context']))
    success_task = Task('success', success, input_from=InputFrom(name=ctx_task_name, parameters=['context']))
    sql_task.on_success(success_task)
    sql_task.on_failure(err_task)

    tasks.append(success_task)
    tasks.append(err_task)

    w.add_tasks(*tasks)
    w.create()

start()
```

**Comment by flaviuvadan** [comment]
Hi @bnuzhanyu! I just tried a conditional execution using: 
```python
def success():
    print("success")

def error_handle():
    print("error")

def f():
    raise Exception(42)

ws = WorkflowService(...)
w = Workflow('fv-condition-test', ws)

t = Task('t', f, continue_on_error=True, continue_on_fail=True)
s = Task('s', success)
e = Task('e', error_handle)
t.on_success(s)
t.on_failure(e)
w.add_tasks(t, s, e)
w.create()
```
![Screen Shot 2022-04-18 at 1 22 15 PM](https://user-images.githubusercontent.com/18152652/163846944-f38e52b4-6e38-4461-9f36-6d9fa22c4ac7.png)

Now, the examples that were used to test the addition of `on_success`, for example, were performed with single tasks, rather than tasks that use `with_items`, which get turned into task groups by Argo. Currently, one cannot use the on success and on failure features when `with_items` is used (or, equivalently, `InputFrom`) as a consequence of an Argo Workflows default documented here: https://argoproj.github.io/argo-workflows/enhanced-depends-logic/#compatibility-with-dependencies-and-dagtaskcontinueon I think the TLDR is: when `with_items` is used Argo can only execute follow up tasks based on whether all previous tasks in the group failed or any of them succeeded. In addition, the use of `dependencies` is prohibited. I wrangled with some code in Hera to migrate to `depends`, remove `continue_on`, and test out `AnySucceeded` and `AllFailed` and managed to make this workflow:
![Screen Shot 2022-04-18 at 2 06 21 PM](https://user-images.githubusercontent.com/18152652/163853112-c8480037-9be3-4c09-9fdc-4ba5de4473e9.png)

Notice how the success ran because _some_ tasks in the group succeeded but the error did not run because not all have failed.

For your use case, @bnuzhanyu, is it possible to know a priori what `day` to construct an Argo SQL task with? I believe the setup can work if we were to use (pseudocode):
```python
tasks = []
for i, day in enumerate(days):
    query = 'select from {day}'
    t = Task(sql-{i}, sql, func_params=[{query: query}])
    t.on_success(success)
    t.on_failure(failure)
    tasks.append(t)
w.add(*tasks + success + failure)
```
This will result in independent task creations for each SQL day query, with each having its own success/failure handling. Would that work?

**Comment by bnuzhanyu** [comment]
> 
Actually my case is in a cronworkflow, and by each execution we can know the day. 
Also the context has more than a sql parameter.
So I think your solution is not quite suitable for me. But I think AnySucceeded, AllFailed would help if I can use input_from. But now I don't know how to use that, can I directly set depends field in a task?

**Comment by bnuzhanyu** [comment]
> Hi @bnuzhanyu! I just tried a conditional execution using:
> 
> ```python
> def success():
>     print("success")
> 
> def error_handle():
>     print("error")
> 
> def f():
>     raise Exception(42)
> 
> ws = WorkflowService(...)
> w = Workflow('fv-condition-test', ws)
> 
> t = Task('t', f, continue_on_error=True, continue_on_fail=True)
> s = Task('s', success)
> e = Task('e', error_handle)
> t.on_success(s)
> t.on_failure(e)
> w.add_tasks(t, s, e)
> w.create()
> ```
> 
> ![Screen Shot 2022-04-18 at 1 22 15 PM](https://user-images.githubusercontent.com/18152652/163846944-f38e52b4-6e38-4461-9f36-6d9fa22c4ac7.png)
> 
> Now, the examples that were used to test the addition of `on_success`, for example, were performed with single tasks, rather than tasks that use `with_items`, which get turned into task groups by Argo. Currently, one cannot use the on success and on failure features when `with_items` is used (or, equivalently, `InputFrom`) as a consequence of an Argo Workflows default documented here: https://argoproj.github.io/argo-workflows/enhanced-depends-logic/#compatibility-with-dependencies-and-dagtaskcontinueon I think the TLDR is: when `with_items` is used Argo can only execute follow up tasks based on whether all previous tasks in the group failed or any of them succeeded. In addition, the use of `dependencies` is prohibited. I wrangled with some code in Hera to migrate to `depends`, remove `continue_on`, and test out `AnySucceeded` and `AllFailed` and managed to make this workflow: ![Screen Shot 2022-04-18 at 2 06 21 PM](https://user-images.githubusercontent.com/18152652/163853112-c8480037-9be3-4c09-9fdc-4ba5de4473e9.png)
> 
> Notice how the success ran because _some_ tasks in the group succeeded but the error did not run because not all have failed.
> 
> For your use case, @bnuzhanyu, is it possible to know a priori what `day` to construct an Argo SQL task with? I believe the setup can work if we were to use (pseudocode):
> 
> ```python
> tasks = []
> for i, day in enumerate(days):
>     query = 'select from {day}'
>     t = Task(sql-{i}, sql, func_params=[{query: query}])
>     t.on_success(success)
>     t.on_failure(failure)
>     tasks.append(t)
> w.add(*tasks + success + failure)
> ```
> 
> This will result in independent task creations for each SQL day query, with each having its own success/failure handling. Would that work?

Thanks, func_params is ok, but lost the convenience of cronworkflow. I use k8s to start that cronjob. 
Would you have plans to support anySuccess/allFailed?

**Comment by flaviuvadan** [comment]
> Would you have plans to support anySuccess/allFailed?

This is not a big change actually so I can definitely add the enhancement mark for someone to contribute it or I can develop it!
