### ISSUE TITLE
How to send folder containing files or images as artifact to a next task?

### ISSUE THREAD

**Issue by sarmientoj24** [argoproj-labs/hera-workflows#170]
So Task A saves bunch of images in a folder. Then Task B needs those images. Is there a way to send those images as an artifact?

**Comment by flaviuvadan** [comment]
Hello again @sarmientoj24! 🙂 Thanks for the question. Passing images between tasks makes dynamically provisioned volumes a good candidate, I think. I would not pass images as canonical Argo artifacts because the storage layer that stores the artifacts is quite limited. Instead, I suggest using volumes:
```python
from hera import Workflow, WorkflowService, Task, Volume, Resources

def foo(images_path='/mnt/images'):
    import download_images

    download_images(images_path)

def bar(images_path='/mnt/images'):
    import process_images

    process_images(images_path)

ws = WorkflowService(...)
w = Workflow(..., ws)
shared_volume = Volume(mount_path='/mnt/images', size='10Gi')
foo_t = Task('foo', foo, resources=Resources(volumes=[shared_volume]))
bar_t = Task('bar', bar, resources=Resources(volumes=[shared_volume]))
foo_t >> bar_t 
w.add_tasks(foo_t, bar_t)
w.create()
```

The above will:
- create two tasks, a producer of images and a consumer of images
- both mount the _same_ dynamically provisioned volume of 10Gi
- the images are stored at `/mnt/images`
- since the volume is shared, both tasks have access to that volume via the images path
- the producer can store images at that path
- the consumer can consume images from that path

These are the concepts used:
- https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/resources.py#L10
- https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/volumes.py#L174

**Comment by sarmientoj24** [comment]
That is awesome @flaviuvadan 
Just another question. What if I dynamically create a parallel "DAG" (say, 2). where each parallel task group should only have access to their specific image sets.

Is the following a good convention? Or will Parallel Group 2 be able to access Parallel Group 1's volume by accident?

Parallel Group 1  
`A_1 >> B_1` using `v1 = Volume(mount_path='/mnt/images', size='10Gi')`  

Parallel Group 2
`A_2 >> B_2` using `v2 = Volume(mount_path='/mnt/images', size='10Gi')`

**Comment by flaviuvadan** [comment]
I do not think this will happen. The [volume gets a UUID assigned to it](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/volumes.py#L65) and if you share a specific volume between the tasks of a chain of tasks only those ones will get the volume attached. If you have, say, a for loop that keeps making these chains like so
```python
w = Workflow(...)
for _ in range(5):
    r = Resources(volumes=[Volume(...)])
    a = Task(..., r=r)
    b = Task(..., r=r)
    a >> b
    w.add_tasks(a, b)
```
then there will be 5 chains of 2 tasks in the workflow, with each chain having access to different volumes.

**Comment by flaviuvadan** [comment]
Any chance you'd like to contribute some of your examples to the `examples` folder with some docs? 🙂 You asked about some interesting scenarios that may benefit others as well!

**Comment by sarmientoj24** [comment]
@flaviuvadan Awesome! I apologize for a lot of questions. Some things I can understand from reading the source code itself, some I dont really know the proper syntax. But great work.

> Any chance you'd like to contribute some of your examples to the examples folder with some docs?   

Sure thing. Just finishing this workflow and will contribute some things in the examples once we make it work properly.
Great work!

**Comment by flaviuvadan** [comment]
All questions are welcome!! 🙂 No apology needed.
