### ISSUE TITLE
How to activate conda environment in Task base image

### ISSUE THREAD

**Issue by ArSin2002** [argoproj-labs/hera-workflows#195]
I am using a custom base image for my Hera Task. The function that the task is going to use requires some library which is already installed in the conda environment of the base image. I want to know how could I activate the conda environment first and then run the python script which is passed as a function to this task?

**Comment by flaviuvadan** [comment]
Hi @ArSin2002! Thanks for the question 🙂 I am not too familiar with conda but I did a quick search to understand whether one can launch a script through the virtual environment. There's a [conda run](https://docs.conda.io/projects/conda/en/latest/commands/run.html) command, which can take a script to run. The `command` field of the `Task` is specifically for this purpose. The default of the `command` field is `python`, which is a command that executes in the environment of the Docker image listed in the `image` field of the `Task`. In your case, I believe you need to use `Task(..., command=["conda", "run", "-n", "my-python-env"]`. If you don't know the name of the environment already and would like to activate it first you have 2 options, I think:
- either create it inside the Docker image with a custom name so it's ready for use with the `-n` reference
- expand the command so it performs `Task(..., command=["conda", "create", "-y", "-n", "my-env", "&&", "conda", "run", "-n", "my-env"]. Note that there's no need to add a script name at the end because Argo already has a reference to the filename that stores the script created with the body of the function you pass to `Task`

Let me know if this helps!

**Comment by ArSin2002** [comment]
> Hi @ArSin2002! Thanks for the question 🙂 I am not too familiar with conda but I did a quick search to understand whether one can launch a script through the virtual environment. There's a [conda run](https://docs.conda.io/projects/conda/en/latest/commands/run.html) command, which can take a script to run. The `command` field of the `Task` is specifically for this purpose. The default of the `command` field is `python`, which is a command that executes in the environment of the Docker image listed in the `image` field of the `Task`. In your case, I believe you need to use `Task(..., command=["conda", "run", "-n", "my-python-env"]`. If you don't know the name of the environment already and would like to activate it first you have 2 options, I think:
> 
> * either create it inside the Docker image with a custom name so it's ready for use with the `-n` reference
> * expand the command so it performs `Task(..., command=["conda", "create", "-y", "-n", "my-env", "&&", "conda", "run", "-n", "my-env"]. Note that there's no need to add a script name at the end because Argo already has a reference to the filename that stores the script created with the body of the function you pass to Task
> 
> Let me know if this helps!

Tired that, it throws permission denied error:
`time="2022-06-19T11:14:44.790Z" level=info msg="capturing logs" argo=true
/tmp/tmpex2vknmc: line 3: /argo/staging/script: Permission denied

ERROR conda.cli.main_run:execute(49): `conda run /argo/staging/script` failed. (See above for error)
Error: exit status 126

`

**Comment by ArSin2002** [comment]
@flaviuvadan any idea how can I provide this permission? I tried `chmod`, but it didn't work.

**Comment by flaviuvadan** [comment]
@ArSin2002 how about `command=['sh', 'conda', ...]`? This is based on this reply from Alex https://github.com/argoproj/argo-workflows/issues/3496#issuecomment-661932342
