### ISSUE TITLE
Step-Level Memoisation Feature 

### ISSUE THREAD

**Issue by munachisonwadike** [argoproj-labs/hera-workflows#196]
Hello! 👋🏾👋🏾
I am currently trying to make use of the step-level memoization feature of hera. 
I tried to add memoisation to the containerisation example found [[here](https://github.com/argoproj-labs/hera-workflows/blob/69a996731ee0c7d10e12838b7e9e5d1fa3540dc4/examples/container.py)]. My code looks like this:

```
from hera import (
	GlobalInputParameter, Input, Memoize, Task, Workflow, WorkflowService
	)
def say(a: str):
    print(a)
ws = WorkflowService(host='https://localhost:2746/', token=token, verify_ssl=False)
w = Workflow('container', service=ws, namespace="argo")

t = Task('cowsay', say, [{'a':1}], #also tried to pass "None" instead of say function since I just needed docker container commands to run
	image='docker/whalesay', 	
	command=['cowsay', 'foo'], memoize=Memoize('a', 'cache1', '5m'))
w.add_task(t)
w.create()
```
When I run it, I get the below error in the argo dashboard:

<img width="400" alt="stack" src="https://user-images.githubusercontent.com/22077758/174459834-a890eae8-b046-4a2e-960d-0792439de969.png">

Also, if I try to change the value of parameter 'a' from the number 1 to a string, such as 'barackobama', I get the below error:

<img width="400" alt="stack" src="https://user-images.githubusercontent.com/22077758/174459896-bba6d8a5-3920-46bd-9f86-9d1c3ea5f2de.png">

I suspect that there is a chance I am not using memoization correctly.
Would there be any examples I could follow for how to use memoization correctly with Hera please?

Warm regards,

**Comment by flaviuvadan** [comment]
Hi @munachisonwadike! Thanks for submitting the issue 🙂 will take a look at this as part of Hera 3.6.0!

**Comment by flaviuvadan** [comment]
@munachisonwadike I figured out the problem. One of them is that a name for the configmap was not specified, so I introduced that. One aspect of Hera's memoization support is that only input parameter caching is supported at the moment rather than input and output caching. I will add an example in 3.6.0. In the mean time, you can check out #212! I also added some screenshots of memoization at play. Hope the example will help! Let me know how it goes for you 🙂
