### ISSUE TITLE
Investigate python -> expr/argo expression language converter

### ISSUE THREAD

**Issue by samj1912** [argoproj-labs/hera-workflows#336]
Currently one of the biggest pain points WRT argo yamls is the expression syntax and manually typing that.

If we could somehow provide a nice wrapper that transpiles python code -> argo expression syntax that would be amazing and would help a lot.

Could be something like

```python
import hera.expr as f

# f.C converts the input to a constant literal
out = f.C(42) + f.C(32)
out.expression() == "42 + 32"

out2 = f.C([1, 2, 3]).map(F.mul(2))

out2.expression = "map([1, 2, 3], { # * 2 })"

# alternatively, not sure if this is possible but

out3 = f.C([1, 2, 3]).map(lambda x: x * 2)

out3.expression = "map([1, 2, 3], { # * 2 })"


```

Not sure how much of this is possible but this would be a huge improvement if this was available.

**Comment by samj1912** [comment]
We can also use https://pypi.org/project/jsonpath-ng/ to help with the jsonpath manipulation using 

`Programmatic JSONPath` options it provides.

**Comment by flaviuvadan** [comment]
This would be a super neat feature :) @Trollgeir and I had some conversations about the complexity of the expression syntax and, so far, we have not attempted something in that area because the universe of possible expression is immense. However, we can build something that _slowly_ progresses to encapsulate some of that complexity, and your suggestion is a great start, IMO! I will take a stab at it and put up a PR for discussion (_probably_ this weekend, if not next week sometime)

**Comment by samj1912** [comment]
Happy to help with the syntax mapping and expression language in Python. I can come up with more concrete examples. I believe it should be possible to have a fairly readable language by using python dunder functions.
