### ISSUE TITLE
Suggestion: Improve example documentation generation 

### ISSUE THREAD

**Issue by samj1912** [argoproj-labs/hera-workflows#349]
Currently I see that the examples directory has to be manually synced between the python examples and the markdown ones. Could we somehow have tooling that auto-generates the markdown examples from python ones? This would help keep the two directories in sync and potentially improve the contribution experience.

**Comment by flaviuvadan** [comment]
That is correct @samj1912 While I think there are solutions to this I fear we might have a hard time doing the translation to an RTD example 100% correctly, all the time, particularly if contributors add explanations as comments around the example code. What if, instead of going from Python to MD we go from MD to Python? That is, we first switch all examples to Markdown exclusively (delete the examples folder). Then, we add a script that parses out the code content between backtick characters, [as others have tried](https://stackoverflow.com/questions/50596431/how-do-i-extract-code-from-markdown-code-block-string)? I do worry about user confusion, though... perhaps documentation an `examples/README` can alleviate the confusion? Thoughts?

**Comment by samj1912** [comment]
MD to Python also sgtm. As long as we have some way to generate one from the other.
