### ISSUE TITLE
Issue while specifying resources in task

### ISSUE THREAD

**Issue by kavitajoshi14** [argoproj-labs/hera-workflows#358]
when we are adding resource in the task and trying to print w.to_yaml , we are having this issue 
![image](https://user-images.githubusercontent.com/98482866/202173099-be82df8a-c190-4b75-93f7-7eac709754d6.png)

**Comment by Trollgeir** [comment]
Could you please show us your code to reproduce this?

**Comment by flaviuvadan** [comment]
The error suggests that the line 
```python
resources=self.resources.build()
```
uses a list type for `resources` rather than a [Resources](https://github.com/argoproj-labs/hera-workflows/blob/main/src/hera/resources.py#L28) object. Any chance the task accidentally received
```python
Task(..., resources=[Resources(...), Resources(...)])
```
or something like that? The `resources` field expected a single `Resources` object

**Comment by kavitajoshi14** [comment]
![image](https://user-images.githubusercontent.com/98482866/202376723-2318c432-8387-4bbb-9752-3e39bdf05c38.png)
i have specified resources in this way

**Comment by kavitajoshi14** [comment]
yes yes before i passed as lists, now passed as in object so it is working now properly.
