### ISSUE TITLE
CronWorkflow name attribute question

### ISSUE THREAD

**Issue by bobh66** [argoproj-labs/hera-workflows#61]
The CronWorkflow object suspend and resume methods have a required name parameter.  Can this parameter be optional and default to the name attribute of the CronWorkflow?

**Comment by flaviuvadan** [comment]
Hey @bobh66! Thanks for submitting this question! 🙂 

Yes, I think this would be a nice addition! I just looked through the `CronWorkflow` and I think I may have missed the fact that we merged this with a required parameter, rather than no `name` parameter, actually. So, I must first apologize for this... I will pay more attention to this type of detail going forward! 

I think I completely agree with your implicit assessment that it should default to `self.name` upon submission. The service can still maintain the interface that requires a `name` because it can be used independently of the `CronWorkflow` object. 

Would you like to submit a PR? 🙂

**Comment by bobh66** [comment]
Thanks @flaviuvadan - I'll push a PR as soon as I'm done with the labels work.

**Comment by flaviuvadan** [comment]
Going to close this for now and continue the discussion on a PR 🙂 Thank you @bobh66!
