### ISSUE TITLE
Workflows of workflows support

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera-workflows#88]
https://argoproj.github.io/argo-workflows/workflow-of-workflows/

**Comment by dixon1e** [comment]
This is one of the primary requests from our scientists.

**Comment by bchalk101** [comment]
The requirement for this has re-arisen for us, specifically we now are having to implement stateful sets for daemons, as seen here https://github.com/argoproj/argo-workflows/blob/master/examples/daemoned-stateful-set-with-service.yaml

Happy to jump onto implementing it, if its not being worked on otherwise.

**Comment by 100mi** [comment]
Hey, I was wondering if there is a reference example for implementing `workflow-of-workflows` using hera-workflows ?

**Comment by flaviuvadan** [comment]
Going to be released in V4
